---
# tasks file for install_services
- name: Install Wget
  yum:
    name:
     - wget
    state: latest

- name: Download JAVA JDK
  shell: |
    wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm"

- name: Install JAVA JDK
  yum:
    name:
     - jdk-8u131-linux-x64.rpm


- name: Download jenkins.war
  get_url:
    dest: /opt/jenkins
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war

- name: Install nginx
  yum:
    name:
      - nginx
    state: latest
